# Generated by Django 5.1.3 on 2024-12-02 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location_type',
            field=models.CharField(choices=[('India', 'India'), ('Nepal', 'Nepal'), ('Bangladesh', 'Bangladesh'), ('Tibet', 'Tibet'), ('Bhutan', 'Bhutan')], default='India', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='religion_type',
            field=models.CharField(choices=[('Spritual', 'Spritual'), ('Buddhist', 'Buddhist'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Muslim', 'Muslim')], default='Hindu', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
